package data

/**
 * this class represents the response message that a requesting node received
 * 
 * @author zepeng zhao
 */
class Responses() extends Serializable {
  //String represents the requesting id generated by the chord when a request is raised.
  private var responses:Map[String, Set[Entry]] = Map()
  
  def containsKey(id:String):Boolean = responses.contains(id)
  
  def remove(id:String):Set[Entry] = {
    var res:Set[Entry] = null
    if(this.containsKey(id)){
      res = this.get(id)
      this.responses = this.responses.filterKeys(_!=id)
    }
    res
  }
  
  private def get(id:String):Set[Entry] = responses(id)
  
  def receive(id:String, e:Set[Entry]){
    this.responses = this.responses+(id->e)   
  }    
}